name:                OpenDE
version:             0.1.0.0
github:              "vitalibarozzi/OpenDE"
license:             BSD-3-Clause
author:              "Joao Vitor Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2024 Joao Vitor Vitali Barozzi"

dependencies:
- base     >= 4.9 && < 5
- array    >= 0.5
- StateVar >= 1.2

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists
- -Wno-unused-matches

library:
  source-dirs: src
  extra-libraries: [ ode, stdc++ ]

tests:
  OpenDE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OpenDE
    - hspec
