name:                OpenDE
version:             0.1.0.0
github:              "vitalibarozzi/OpenDE"
license:             BSD-3-Clause
author:              "Joao Vitor Vitali Barozzi"
maintainer:          "vitalivitor@gmail.com"
copyright:           "2024 Joao Vitor Vitali Barozzi"

dependencies:
- base >= 4.7 && < 5
- array # cosntrain it more?
- StateVar # cosntrain it more?
- linear # cosntrain it more?

ghc-options:
- -Wall
#- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  extra-libraries: [ ode, stdc++ ]

tests:
  OpenDE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OpenDE
    - hspec
