resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/22.yaml
packages:
- .
nix:
  packages:
    - ode
    - llvmPackages_14.libcxx
    - llvmPackages_14.libcxxabi

